name: "LMVT"
input_size: 224
num_classes: 5
dropout_rate: 0.3

# LMVT-specific
depthwise_channels: 64
transformer_heads: 4
transformer_layers: 2

# Optimization
optimizer: "adam"
learning_rate: 0.0001
weight_decay: 0.00001
scheduler: "cosine"
